version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment_form_db
    networks:
      - my-docker-network

  app:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    ports:
      - "443:443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/payment_form_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    networks:
      - my-docker-network

networks:
  my-docker-network:
    driver: bridge